/**
 * 数据库安全基线配置
 * 12 种数据库，约 100+ 可编辑项
 */

import type { BaselineCategory, BaselineConfigItem } from './baselineConfigs';

// ─── 辅助函数 ───

function escapeSedReplacement(s: string): string {
  return s.replace(/[\\/&\n]/g, '\\$&');
}

function escapeShellSingleQuote(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function sedOrAppend(file: string, key: string, value: string): string {
  const safeValue = escapeSedReplacement(value);
  const shellSafe = escapeShellSingleQuote(value);
  return `grep -qiE '^#?\\s*${key}\\b' ${file} && sed -i 's/^#*\\s*${key}\\b.*/${key} ${safeValue}/' ${file} || echo '${key} ${shellSafe}' >> ${file}`;
}

function sedOrAppendEq(file: string, key: string, value: string): string {
  const safeValue = escapeSedReplacement(value);
  const shellSafe = escapeShellSingleQuote(value);
  return `grep -qE '^#?\\s*${key}\\b' ${file} && sed -i 's/^#*\\s*${key}\\b.*/${key}\\t${safeValue}/' ${file} || echo '${key}\t${shellSafe}' >> ${file}`;
}

function backup(file: string): string {
  return `cp -n ${file} ${file}_bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`;
}

// ─── MySQL / MariaDB ───

const mysqlItems: BaselineConfigItem[] = [
  {
    id: 'mysql-bind-address',
    name: 'bind-address',
    description: '数据库监听地址，建议绑定 127.0.0.1 禁止外部直连',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'string',
    defaultValue: '0.0.0.0',
    recommendedValue: '127.0.0.1',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*bind-address' /etc/mysql/mysql.conf.d/mysqld.cnf /etc/my.cnf /etc/mysql/my.cnf 2>/dev/null | head -1 || echo '#bind-address not set'`,
    parseRegex: 'bind-address\\s*=\\s*(\\S+)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'bind-address', v),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 网络安全',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        readCommand: `grep -E '^\\s*bind-address' /etc/my.cnf /etc/my.cnf.d/*.cnf 2>/dev/null | head -1 || echo '#bind-address not set'`,
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'bind-address', v),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-local-infile',
    name: 'local_infile',
    description: '控制 LOAD DATA LOCAL INFILE，建议关闭以防止客户端读取服务器本地文件',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'ON',
    recommendedValue: 'OFF',
    riskLevel: 'high',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'local_infile'" 2>/dev/null | grep -i local_infile | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'local-infile', v === 'ON' ? '1' : '0'),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 安全计算环境',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'local-infile', v === 'ON' ? '1' : '0'),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-symbolic-links',
    name: 'symbolic-links',
    description: '禁用符号链接，防止通过软链接访问未授权文件',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'ON',
    recommendedValue: 'OFF',
    riskLevel: 'high',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'have_symlink'" 2>/dev/null | grep -i have_symlink | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(YES|DISABLED|ON|OFF|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'symbolic-links', v === 'ON' ? '1' : '0'),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 安全计算环境',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'symbolic-links', v === 'ON' ? '1' : '0'),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-ssl',
    name: 'require_secure_transport',
    description: '强制 SSL/TLS 加密连接，防止明文传输敏感数据',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'critical',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'require_secure_transport'" 2>/dev/null | grep -i require_secure_transport | awk '{print $2}' || mysql -u root -e "SHOW VARIABLES LIKE 'have_ssl'" 2>/dev/null | grep -i have_ssl | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|YES|DISABLED|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'require_secure_transport', v),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 通信安全',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'require_secure_transport', v),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-log-bin',
    name: 'log_bin',
    description: '二进制日志，用于数据恢复和主从复制，建议开启',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'medium',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'log_bin'" 2>/dev/null | grep -i log_bin | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|unknown)',
    writeCommand: (v) => {
      if (v === 'ON') {
        return sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'log-bin', 'mysql-bin');
      }
      return `sed -i '/^\\s*log-bin/d' /etc/mysql/mysql.conf.d/mysqld.cnf; echo 'skip-log-bin' >> /etc/mysql/mysql.conf.d/mysqld.cnf`;
    },
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 数据备份恢复',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => {
          if (v === 'ON') {
            return sedOrAppendEq('/etc/my.cnf', 'log-bin', 'mysql-bin');
          }
          return `sed -i '/^\\s*log-bin/d' /etc/my.cnf; echo 'skip-log-bin' >> /etc/my.cnf`;
        },
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-general-log',
    name: 'general_log',
    description: '通用查询日志，记录所有 SQL 操作，建议生产环境关闭（性能影响大）',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'OFF',
    riskLevel: 'low',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'general_log'" 2>/dev/null | grep -i general_log | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'general-log', v === 'ON' ? '1' : '0'),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 安全审计',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'general-log', v === 'ON' ? '1' : '0'),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-password-policy',
    name: 'validate_password.policy',
    description: '密码强度策略，建议设置为 MEDIUM 或 STRONG',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['LOW', 'MEDIUM', 'STRONG'],
    defaultValue: 'LOW',
    recommendedValue: 'MEDIUM',
    riskLevel: 'high',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'validate_password%policy'" 2>/dev/null | grep -i policy | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(LOW|MEDIUM|STRONG|0|1|2|unknown)',
    writeCommand: (v) => `mysql -u root -e "SET GLOBAL validate_password.policy='${v}'" 2>/dev/null || mysql -u root -e "SET GLOBAL validate_password_policy='${v}'" 2>/dev/null`,
    backupCommand: 'true',
    restartService: 'mysql',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'mysql-max-connections',
    name: 'max_connections',
    description: '最大并发连接数，根据业务需求合理配置',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'number',
    defaultValue: '151',
    recommendedValue: '500',
    riskLevel: 'medium',
    validation: { min: 10, max: 100000 },
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'max_connections'" 2>/dev/null | grep -i max_connections | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(\\d+|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'max-connections', v),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 资源控制',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'max-connections', v),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-default-auth',
    name: 'default_authentication_plugin',
    description: '默认身份验证插件，建议使用 caching_sha2_password',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'string',
    defaultValue: 'mysql_native_password',
    recommendedValue: 'caching_sha2_password',
    riskLevel: 'high',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'default_authentication_plugin'" 2>/dev/null | grep -i default_authentication_plugin | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(\\S+)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'default-authentication-plugin', v),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 身份鉴别',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'default-authentication-plugin', v),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-anonymous-users',
    name: '匿名用户',
    description: '检查是否存在匿名用户（空用户名），建议删除',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['存在', '不存在'],
    defaultValue: '存在',
    recommendedValue: '不存在',
    riskLevel: 'critical',
    readCommand: `result=$(mysql -u root -e "SELECT COUNT(*) AS c FROM mysql.user WHERE User=''" 2>/dev/null | tail -1); if [ "$result" = "0" ]; then echo '不存在'; else echo '存在'; fi`,
    parseRegex: '(存在|不存在)',
    writeCommand: (_v) => `mysql -u root -e "DELETE FROM mysql.user WHERE User=''; FLUSH PRIVILEGES;" 2>/dev/null`,
    backupCommand: `mysqldump -u root mysql user > /tmp/mysql_user_backup_$(date +%Y%m%d%H%M%S).sql 2>/dev/null; true`,
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'mysql-test-db',
    name: 'test 数据库',
    description: '检查是否存在 test 数据库，建议删除以减少攻击面',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['存在', '不存在'],
    defaultValue: '存在',
    recommendedValue: '不存在',
    riskLevel: 'medium',
    readCommand: `result=$(mysql -u root -e "SHOW DATABASES LIKE 'test'" 2>/dev/null | grep -c test); if [ "$result" = "0" ]; then echo '不存在'; else echo '存在'; fi`,
    parseRegex: '(存在|不存在)',
    writeCommand: (_v) => `mysql -u root -e "DROP DATABASE IF EXISTS test;" 2>/dev/null`,
    backupCommand: `mysqldump -u root test > /tmp/mysql_test_db_backup_$(date +%Y%m%d%H%M%S).sql 2>/dev/null; true`,
    complianceRef: '等保2.0 安全计算环境',
  },
  {
    id: 'mysql-remote-root',
    name: 'root 远程登录',
    description: '检查 root 是否允许远程登录，建议禁止',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['允许', '禁止'],
    defaultValue: '允许',
    recommendedValue: '禁止',
    riskLevel: 'critical',
    readCommand: `result=$(mysql -u root -e "SELECT COUNT(*) AS c FROM mysql.user WHERE User='root' AND Host='%'" 2>/dev/null | tail -1); if [ "$result" = "0" ]; then echo '禁止'; else echo '允许'; fi`,
    parseRegex: '(允许|禁止)',
    writeCommand: (_v) => `mysql -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host='%'; FLUSH PRIVILEGES;" 2>/dev/null`,
    backupCommand: `mysqldump -u root mysql user > /tmp/mysql_user_backup_$(date +%Y%m%d%H%M%S).sql 2>/dev/null; true`,
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'mysql-audit-log',
    name: 'audit_log',
    description: '审计日志插件，记录数据库操作用于合规审计',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'high',
    readCommand: `mysql -u root -e "SELECT PLUGIN_STATUS FROM INFORMATION_SCHEMA.PLUGINS WHERE PLUGIN_NAME='audit_log'" 2>/dev/null | tail -1 || echo 'OFF'`,
    parseRegex: '(ACTIVE|ON|OFF|INACTIVE)',
    writeCommand: (v) => {
      if (v === 'ON') {
        return `mysql -u root -e "INSTALL PLUGIN audit_log SONAME 'audit_log.so'" 2>/dev/null; true`;
      }
      return `mysql -u root -e "UNINSTALL PLUGIN audit_log" 2>/dev/null; true`;
    },
    backupCommand: 'true',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'mysql-secure-auth',
    name: 'secure_auth',
    description: '禁止旧版不安全的认证方式（pre-4.1 密码哈希）',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'ON',
    recommendedValue: 'ON',
    riskLevel: 'medium',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'secure_auth'" 2>/dev/null | grep -i secure_auth | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|unknown)',
    writeCommand: (v) => sedOrAppendEq('/etc/mysql/mysql.conf.d/mysqld.cnf', 'secure-auth', v === 'ON' ? '1' : '0'),
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 身份鉴别',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => sedOrAppendEq('/etc/my.cnf', 'secure-auth', v === 'ON' ? '1' : '0'),
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
  {
    id: 'mysql-skip-networking',
    name: 'skip-networking',
    description: '完全禁用 TCP/IP 网络连接，仅允许本地 socket 连接',
    filePath: '/etc/mysql/mysql.conf.d/mysqld.cnf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'OFF',
    riskLevel: 'medium',
    readCommand: `mysql -u root -e "SHOW VARIABLES LIKE 'skip_networking'" 2>/dev/null | grep -i skip_networking | awk '{print $2}' || echo 'unknown'`,
    parseRegex: '(ON|OFF|unknown)',
    writeCommand: (v) => {
      if (v === 'ON') {
        return sedOrAppend('/etc/mysql/mysql.conf.d/mysqld.cnf', 'skip-networking', '');
      }
      return `sed -i '/^\\s*skip-networking/d' /etc/mysql/mysql.conf.d/mysqld.cnf`;
    },
    backupCommand: backup('/etc/mysql/mysql.conf.d/mysqld.cnf'),
    restartCommand: 'systemctl restart mysql 2>/dev/null || systemctl restart mysqld 2>/dev/null || systemctl restart mariadb 2>/dev/null',
    restartService: 'mysql',
    complianceRef: '等保2.0 网络安全',
    distroOverrides: {
      redhat: {
        filePath: '/etc/my.cnf',
        writeCommand: (v: string) => {
          if (v === 'ON') {
            return sedOrAppend('/etc/my.cnf', 'skip-networking', '');
          }
          return `sed -i '/^\\s*skip-networking/d' /etc/my.cnf`;
        },
        backupCommand: backup('/etc/my.cnf'),
      },
    },
  },
];

// ─── PostgreSQL ───

const pgConf = '/etc/postgresql/*/main/postgresql.conf';
const pgHba = '/etc/postgresql/*/main/pg_hba.conf';
const pgConfRh = '/var/lib/pgsql/*/data/postgresql.conf';
const pgHbaRh = '/var/lib/pgsql/*/data/pg_hba.conf';

const postgresqlItems: BaselineConfigItem[] = [
  {
    id: 'pg-listen-addresses',
    name: 'listen_addresses',
    description: '监听地址，建议绑定特定 IP 而非 * 以限制访问',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'string',
    defaultValue: 'localhost',
    recommendedValue: 'localhost',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*listen_addresses' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo "#listen_addresses = 'localhost'"`,
    parseRegex: "listen_addresses\\s*=\\s*'([^']*)'",
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); ${sedOrAppendEq('$PG_CONF', 'listen_addresses', `'${v}'`)}`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart postgresql 2>/dev/null || pg_ctl restart -D /var/lib/pgsql/data 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'pg-ssl',
    name: 'ssl',
    description: '启用 SSL 加密连接，防止数据传输被窃听',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*ssl\\s*=' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo '#ssl = off'`,
    parseRegex: 'ssl\\s*=\\s*(on|off)',
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*ssl\\s*=.*/ssl = ${v}/" $PG_CONF || echo "ssl = ${v}" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'pg-password-encryption',
    name: 'password_encryption',
    description: '密码加密算法，建议使用 scram-sha-256 替代 md5',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['scram-sha-256', 'md5'],
    defaultValue: 'md5',
    recommendedValue: 'scram-sha-256',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*password_encryption' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo "#password_encryption = 'md5'"`,
    parseRegex: "password_encryption\\s*=\\s*'?([\\w-]+)",
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*password_encryption.*/password_encryption = '${v}'/" $PG_CONF || echo "password_encryption = '${v}'" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'pg-log-connections',
    name: 'log_connections',
    description: '记录所有连接尝试日志，便于审计追踪',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_connections' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo '#log_connections = off'`,
    parseRegex: 'log_connections\\s*=\\s*(on|off)',
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*log_connections.*/log_connections = ${v}/" $PG_CONF || echo "log_connections = ${v}" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'pg-log-disconnections',
    name: 'log_disconnections',
    description: '记录所有断开连接日志，配合 log_connections 完整审计',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_disconnections' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo '#log_disconnections = off'`,
    parseRegex: 'log_disconnections\\s*=\\s*(on|off)',
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*log_disconnections.*/log_disconnections = ${v}/" $PG_CONF || echo "log_disconnections = ${v}" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'pg-log-statement',
    name: 'log_statement',
    description: '控制哪些 SQL 语句被记录到日志（none/ddl/mod/all）',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['none', 'ddl', 'mod', 'all'],
    defaultValue: 'none',
    recommendedValue: 'ddl',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_statement' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo "#log_statement = 'none'"`,
    parseRegex: "log_statement\\s*=\\s*'?(none|ddl|mod|all)",
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*log_statement.*/log_statement = '${v}'/" $PG_CONF || echo "log_statement = '${v}'" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'pg-hba-trust',
    name: 'pg_hba trust 条目数',
    description: 'pg_hba.conf 中 trust 认证条目数量，建议为 0',
    filePath: '/etc/postgresql/main/pg_hba.conf',
    type: 'number',
    defaultValue: '0',
    recommendedValue: '0',
    riskLevel: 'critical',
    readCommand: `grep -cE '^\\s*(local|host).*trust' ${pgHba} ${pgHbaRh} 2>/dev/null | grep -v ':0$' | head -1 || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (_v) => `PG_HBA=$(find /etc/postgresql /var/lib/pgsql -name pg_hba.conf 2>/dev/null | head -1); sed -i 's/\\btrust\\b/scram-sha-256/g' $PG_HBA`,
    backupCommand: `PG_HBA=$(find /etc/postgresql /var/lib/pgsql -name pg_hba.conf 2>/dev/null | head -1); cp -n $PG_HBA $PG_HBA.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'pg-hba-md5',
    name: 'pg_hba md5 条目数',
    description: 'pg_hba.conf 中 md5 认证条目数量，建议迁移到 scram-sha-256',
    filePath: '/etc/postgresql/main/pg_hba.conf',
    type: 'number',
    defaultValue: '0',
    recommendedValue: '0',
    riskLevel: 'medium',
    readCommand: `grep -cE '^\\s*(local|host).*md5' ${pgHba} ${pgHbaRh} 2>/dev/null | grep -v ':0$' | head -1 || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (_v) => `PG_HBA=$(find /etc/postgresql /var/lib/pgsql -name pg_hba.conf 2>/dev/null | head -1); sed -i 's/\\bmd5\\b/scram-sha-256/g' $PG_HBA`,
    backupCommand: `PG_HBA=$(find /etc/postgresql /var/lib/pgsql -name pg_hba.conf 2>/dev/null | head -1); cp -n $PG_HBA $PG_HBA.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl reload postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'pg-superuser-reserved',
    name: 'superuser_reserved_connections',
    description: '为超级用户保留的连接数，确保管理员始终可以登录',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'number',
    defaultValue: '3',
    recommendedValue: '5',
    riskLevel: 'low',
    validation: { min: 1, max: 100 },
    readCommand: `grep -E '^\\s*superuser_reserved_connections' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo '#superuser_reserved_connections = 3'`,
    parseRegex: 'superuser_reserved_connections\\s*=\\s*(\\d+)',
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*superuser_reserved_connections.*/superuser_reserved_connections = ${v}/" $PG_CONF || echo "superuser_reserved_connections = ${v}" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'pg-max-connections',
    name: 'max_connections',
    description: '最大并发连接数，根据业务需求合理配置',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'number',
    defaultValue: '100',
    recommendedValue: '200',
    riskLevel: 'medium',
    validation: { min: 10, max: 100000 },
    readCommand: `grep -E '^\\s*max_connections' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo '#max_connections = 100'`,
    parseRegex: 'max_connections\\s*=\\s*(\\d+)',
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*max_connections.*/max_connections = ${v}/" $PG_CONF || echo "max_connections = ${v}" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'pg-shared-preload',
    name: 'shared_preload_libraries',
    description: '预加载共享库，建议包含 pg_stat_statements 用于性能监控',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'string',
    defaultValue: '',
    recommendedValue: 'pg_stat_statements',
    riskLevel: 'low',
    readCommand: `grep -E '^\\s*shared_preload_libraries' ${pgConf} ${pgConfRh} 2>/dev/null | head -1 || echo "#shared_preload_libraries = ''"`,
    parseRegex: "shared_preload_libraries\\s*=\\s*'([^']*)'",
    writeCommand: (v) => `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); sed -i "s/^#*\\s*shared_preload_libraries.*/shared_preload_libraries = '${v}'/" $PG_CONF || echo "shared_preload_libraries = '${v}'" >> $PG_CONF`,
    backupCommand: `PG_CONF=$(find /etc/postgresql /var/lib/pgsql -name postgresql.conf 2>/dev/null | head -1); cp -n $PG_CONF $PG_CONF.bak_$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart postgresql 2>/dev/null',
    restartService: 'postgresql',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'pg-data-checksums',
    name: 'data_checksums',
    description: '数据页校验和，防止存储损坏导致数据静默错误',
    filePath: '/etc/postgresql/main/postgresql.conf',
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'medium',
    readCommand: `su - postgres -c "psql -tAc 'SHOW data_checksums'" 2>/dev/null || echo 'off'`,
    parseRegex: '(on|off)',
    writeCommand: (_v) => `echo '数据校验和需在 initdb 时启用或使用 pg_checksums 工具离线开启，无法在线修改'; true`,
    backupCommand: 'true',
    restartService: 'postgresql',
    complianceRef: '等保2.0 数据完整性',
  },
];

// ─── Redis ───

const redisConf = '/etc/redis/redis.conf';
const redisConfAlt = '/etc/redis.conf';

const redisItems: BaselineConfigItem[] = [
  {
    id: 'redis-bind',
    name: 'bind',
    description: '绑定监听地址，建议绑定 127.0.0.1 禁止外部直连',
    filePath: redisConf,
    type: 'string',
    defaultValue: '0.0.0.0',
    recommendedValue: '127.0.0.1',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*bind ' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#bind not set'`,
    parseRegex: 'bind\\s+(\\S+)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'bind', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'redis-protected-mode',
    name: 'protected-mode',
    description: '保护模式，无密码且监听非回环地址时拒绝外部连接',
    filePath: redisConf,
    type: 'enum',
    enumValues: ['yes', 'no'],
    defaultValue: 'yes',
    recommendedValue: 'yes',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*protected-mode' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#protected-mode yes'`,
    parseRegex: 'protected-mode\\s+(yes|no)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'protected-mode', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'redis-requirepass',
    name: 'requirepass',
    description: '连接认证密码，建议设置强密码',
    filePath: redisConf,
    type: 'enum',
    enumValues: ['已设置', '未设置'],
    defaultValue: '未设置',
    recommendedValue: '已设置',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*requirepass' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 && echo '已设置' || echo '未设置'`,
    parseRegex: '(已设置|未设置)',
    writeCommand: (v) => {
      if (v === '已设置') {
        return `echo '请手动设置 requirepass 为一个强密码'; true`;
      }
      return `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); sed -i 's/^\\s*requirepass/#requirepass/' $REDIS_CONF`;
    },
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'redis-rename-commands',
    name: 'rename-command 高危命令',
    description: '重命名或禁用高危命令（FLUSHALL/FLUSHDB/CONFIG/KEYS 等）',
    filePath: redisConf,
    type: 'enum',
    enumValues: ['已配置', '未配置'],
    defaultValue: '未配置',
    recommendedValue: '已配置',
    riskLevel: 'high',
    readCommand: `grep -cE '^\\s*rename-command' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1; result=$?; count=$(grep -cE '^\\s*rename-command' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1); if [ "$count" -gt "0" ] 2>/dev/null; then echo '已配置'; else echo '未配置'; fi`,
    parseRegex: '(已配置|未配置)',
    writeCommand: (_v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); grep -q 'rename-command FLUSHALL' $REDIS_CONF || echo -e 'rename-command FLUSHALL ""\nrename-command FLUSHDB ""\nrename-command CONFIG ""\nrename-command KEYS ""' >> $REDIS_CONF`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'redis-maxmemory',
    name: 'maxmemory',
    description: '最大内存限制，防止 Redis 耗尽系统内存',
    filePath: redisConf,
    type: 'string',
    defaultValue: '0',
    recommendedValue: '2gb',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*maxmemory ' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#maxmemory not set'`,
    parseRegex: 'maxmemory\\s+(\\S+)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'maxmemory', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'redis-maxclients',
    name: 'maxclients',
    description: '最大客户端连接数，合理限制避免资源耗尽',
    filePath: redisConf,
    type: 'number',
    defaultValue: '10000',
    recommendedValue: '10000',
    riskLevel: 'low',
    validation: { min: 1, max: 1000000 },
    readCommand: `grep -E '^\\s*maxclients' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#maxclients 10000'`,
    parseRegex: 'maxclients\\s+(\\d+)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'maxclients', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'redis-no-appendfsync',
    name: 'no-appendfsync-on-rewrite',
    description: 'AOF 重写期间是否暂停 fsync，建议关闭以保证数据持久性',
    filePath: redisConf,
    type: 'enum',
    enumValues: ['yes', 'no'],
    defaultValue: 'no',
    recommendedValue: 'no',
    riskLevel: 'low',
    readCommand: `grep -E '^\\s*no-appendfsync-on-rewrite' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#no-appendfsync-on-rewrite no'`,
    parseRegex: 'no-appendfsync-on-rewrite\\s+(yes|no)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'no-appendfsync-on-rewrite', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 数据完整性',
  },
  {
    id: 'redis-tls-port',
    name: 'tls-port',
    description: 'TLS 加密端口，建议启用以加密客户端通信',
    filePath: redisConf,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '6380',
    riskLevel: 'high',
    validation: { min: 0, max: 65535 },
    readCommand: `grep -E '^\\s*tls-port' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1 || echo '#tls-port 0'`,
    parseRegex: 'tls-port\\s+(\\d+)',
    writeCommand: (v) => `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); ${sedOrAppend('$REDIS_CONF', 'tls-port', v)}`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'redis-acl',
    name: 'ACL 访问控制',
    description: 'Redis 6+ ACL 功能，细粒度用户权限控制',
    filePath: redisConf,
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `grep -cE '^\\s*user ' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1; count=$(grep -cE '^\\s*user ' ${redisConf} ${redisConfAlt} 2>/dev/null | head -1); if [ "$count" -gt "0" ] 2>/dev/null; then echo '已启用'; else echo '未启用'; fi`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请手动配置 ACL 用户列表或使用 aclfile 指定外部 ACL 文件'; true`,
    backupCommand: `REDIS_CONF=$([ -f ${redisConf} ] && echo ${redisConf} || echo ${redisConfAlt}); cp -n $REDIS_CONF $REDIS_CONF.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    restartCommand: 'systemctl restart redis 2>/dev/null || systemctl restart redis-server 2>/dev/null',
    restartService: 'redis',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'redis-disable-thp',
    name: 'disable-thp',
    description: '禁用 Transparent Huge Pages，避免 Redis 延迟抖动',
    filePath: '/sys/kernel/mm/transparent_hugepage/enabled',
    type: 'enum',
    enumValues: ['已禁用', '未禁用'],
    defaultValue: '未禁用',
    recommendedValue: '已禁用',
    riskLevel: 'medium',
    readCommand: `cat /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null | grep -q '\\[never\\]' && echo '已禁用' || echo '未禁用'`,
    parseRegex: '(已禁用|未禁用)',
    writeCommand: (_v) => `echo never > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null; echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' >> /etc/rc.local; chmod +x /etc/rc.local 2>/dev/null; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 资源控制',
  },
];

// ─── MongoDB ───

const mongoConf = '/etc/mongod.conf';

const mongodbItems: BaselineConfigItem[] = [
  {
    id: 'mongo-auth',
    name: 'security.authorization',
    description: '启用认证授权，防止未授权访问数据库',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['enabled', 'disabled'],
    defaultValue: 'disabled',
    recommendedValue: 'enabled',
    riskLevel: 'critical',
    readCommand: `grep -A5 '^security:' ${mongoConf} 2>/dev/null | grep authorization | awk '{print $2}' || echo 'disabled'`,
    parseRegex: '(enabled|disabled)',
    writeCommand: (v) => `grep -q '^security:' ${mongoConf} && sed -i '/^security:/,/^[^ ]/{s/authorization:.*/authorization: ${v}/}' ${mongoConf} || echo -e "security:\\n  authorization: ${v}" >> ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'mongo-bind-ip',
    name: 'net.bindIp',
    description: '绑定监听地址，建议绑定 127.0.0.1 禁止外部直连',
    filePath: mongoConf,
    type: 'string',
    defaultValue: '0.0.0.0',
    recommendedValue: '127.0.0.1',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*bindIp' ${mongoConf} 2>/dev/null | awk '{print $2}' || echo '0.0.0.0'`,
    parseRegex: 'bindIp:\\s*(\\S+)',
    writeCommand: (v) => `sed -i "s/^\\s*bindIp:.*/  bindIp: ${v}/" ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'mongo-tls',
    name: 'net.tls.mode',
    description: 'TLS 传输加密模式（disabled/allowTLS/preferTLS/requireTLS）',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['disabled', 'allowTLS', 'preferTLS', 'requireTLS'],
    defaultValue: 'disabled',
    recommendedValue: 'requireTLS',
    riskLevel: 'high',
    readCommand: `grep -A10 '^net:' ${mongoConf} 2>/dev/null | grep -E 'mode:' | awk '{print $2}' || echo 'disabled'`,
    parseRegex: '(disabled|allowTLS|preferTLS|requireTLS)',
    writeCommand: (v) => `grep -q 'tls:' ${mongoConf} && sed -i '/tls:/,/mode:/{s/mode:.*/mode: ${v}/}' ${mongoConf} || sed -i '/^net:/a\\  tls:\\n    mode: ${v}' ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'mongo-audit-log',
    name: 'auditLog.destination',
    description: '审计日志输出目标（file/console/syslog），建议启用',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['file', 'console', 'syslog', '未配置'],
    defaultValue: '未配置',
    recommendedValue: 'file',
    riskLevel: 'high',
    readCommand: `grep -A5 '^auditLog:' ${mongoConf} 2>/dev/null | grep destination | awk '{print $2}' || echo '未配置'`,
    parseRegex: '(file|console|syslog|未配置)',
    writeCommand: (v) => `grep -q '^auditLog:' ${mongoConf} && sed -i '/^auditLog:/,/destination:/{s/destination:.*/destination: ${v}/}' ${mongoConf} || echo -e "auditLog:\\n  destination: ${v}\\n  format: JSON\\n  path: /var/log/mongodb/audit.json" >> ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'mongo-scripting',
    name: 'security.javascriptEnabled',
    description: '禁用服务端 JavaScript 执行，防止注入攻击',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['true', 'false'],
    defaultValue: 'true',
    recommendedValue: 'false',
    riskLevel: 'high',
    readCommand: `grep -A5 '^security:' ${mongoConf} 2>/dev/null | grep javascriptEnabled | awk '{print $2}' || echo 'true'`,
    parseRegex: '(true|false)',
    writeCommand: (v) => `grep -q 'javascriptEnabled' ${mongoConf} && sed -i "s/javascriptEnabled:.*/javascriptEnabled: ${v}/" ${mongoConf} || sed -i '/^security:/a\\  javascriptEnabled: ${v}' ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 安全计算环境',
  },
  {
    id: 'mongo-rest',
    name: 'net.http.enabled',
    description: '禁用 HTTP REST 接口，减少攻击面',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['true', 'false'],
    defaultValue: 'false',
    recommendedValue: 'false',
    riskLevel: 'medium',
    readCommand: `grep -A10 '^net:' ${mongoConf} 2>/dev/null | grep -E 'enabled:' | head -1 | awk '{print $2}' || echo 'false'`,
    parseRegex: '(true|false)',
    writeCommand: (v) => `grep -q 'http:' ${mongoConf} && sed -i '/http:/,/enabled:/{s/enabled:.*/enabled: ${v}/}' ${mongoConf} || true`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'mongo-oplog',
    name: 'replication.oplogSizeMB',
    description: 'Oplog 大小，影响复制集同步窗口',
    filePath: mongoConf,
    type: 'number',
    defaultValue: '990',
    recommendedValue: '2048',
    riskLevel: 'low',
    validation: { min: 100, max: 102400 },
    readCommand: `grep -A5 '^replication:' ${mongoConf} 2>/dev/null | grep oplogSizeMB | awk '{print $2}' || echo '990'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `grep -q '^replication:' ${mongoConf} && sed -i '/^replication:/,/oplogSizeMB:/{s/oplogSizeMB:.*/oplogSizeMB: ${v}/}' ${mongoConf} || echo -e "replication:\\n  oplogSizeMB: ${v}" >> ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 数据备份恢复',
  },
  {
    id: 'mongo-wiredtiger-encrypt',
    name: 'storage.wiredTiger.engineConfig.encryptionCipherMode',
    description: 'WiredTiger 存储引擎加密，保护静态数据安全',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['AES256-CBC', 'AES256-GCM', '未配置'],
    defaultValue: '未配置',
    recommendedValue: 'AES256-CBC',
    riskLevel: 'high',
    readCommand: `grep -A20 '^storage:' ${mongoConf} 2>/dev/null | grep encryptionCipherMode | awk '{print $2}' || echo '未配置'`,
    parseRegex: '(AES256-CBC|AES256-GCM|未配置)',
    writeCommand: (_v) => `echo '存储加密需在企业版中配置 encryptionCipherMode 和加密密钥，请参考官方文档'; true`,
    backupCommand: backup(mongoConf),
    restartService: 'mongod',
    complianceRef: '等保2.0 数据保密性',
  },
  {
    id: 'mongo-net-maxconn',
    name: 'net.maxIncomingConnections',
    description: '最大并发连接数，防止连接耗尽',
    filePath: mongoConf,
    type: 'number',
    defaultValue: '65536',
    recommendedValue: '65536',
    riskLevel: 'low',
    validation: { min: 100, max: 1000000 },
    readCommand: `grep -A10 '^net:' ${mongoConf} 2>/dev/null | grep maxIncomingConnections | awk '{print $2}' || echo '65536'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `grep -q 'maxIncomingConnections' ${mongoConf} && sed -i "s/maxIncomingConnections:.*/maxIncomingConnections: ${v}/" ${mongoConf} || sed -i '/^net:/a\\  maxIncomingConnections: ${v}' ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'mongo-security-redact',
    name: 'security.redactClientLogData',
    description: '日志脱敏，防止敏感数据泄露到日志文件',
    filePath: mongoConf,
    type: 'enum',
    enumValues: ['true', 'false'],
    defaultValue: 'false',
    recommendedValue: 'true',
    riskLevel: 'medium',
    readCommand: `grep -A10 '^security:' ${mongoConf} 2>/dev/null | grep redactClientLogData | awk '{print $2}' || echo 'false'`,
    parseRegex: '(true|false)',
    writeCommand: (v) => `grep -q 'redactClientLogData' ${mongoConf} && sed -i "s/redactClientLogData:.*/redactClientLogData: ${v}/" ${mongoConf} || sed -i '/^security:/a\\  redactClientLogData: ${v}' ${mongoConf}`,
    backupCommand: backup(mongoConf),
    restartCommand: 'systemctl restart mongod 2>/dev/null',
    restartService: 'mongod',
    complianceRef: '等保2.0 数据保密性',
  },
];

// ─── Oracle ───

const oraCmd = (sql: string) => `su - oracle -c "echo '${sql}' | sqlplus -s / as sysdba" 2>/dev/null`;

const oracleItems: BaselineConfigItem[] = [
  {
    id: 'oracle-audit-trail',
    name: 'AUDIT_TRAIL',
    description: '审计跟踪模式（NONE/OS/DB/DB_EXTENDED/XML），建议启用',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'enum',
    enumValues: ['NONE', 'OS', 'DB', 'DB_EXTENDED', 'XML'],
    defaultValue: 'NONE',
    recommendedValue: 'DB',
    riskLevel: 'critical',
    readCommand: `${oraCmd("SHOW PARAMETER audit_trail;")} | grep -i audit_trail | awk '{print $NF}'`,
    parseRegex: '(NONE|OS|DB|DB_EXTENDED|XML)',
    writeCommand: (v) => `${oraCmd(`ALTER SYSTEM SET audit_trail='${v}' SCOPE=SPFILE;`)}`,
    backupCommand: 'true',
    restartCommand: `su - oracle -c "echo 'SHUTDOWN IMMEDIATE;\\nSTARTUP;' | sqlplus -s / as sysdba" 2>/dev/null`,
    restartService: 'oracle',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'oracle-failed-login',
    name: 'FAILED_LOGIN_ATTEMPTS',
    description: '登录失败锁定次数，建议不超过 10 次',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'number',
    defaultValue: '10',
    recommendedValue: '5',
    riskLevel: 'high',
    validation: { min: 1, max: 100 },
    readCommand: `${oraCmd("SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='FAILED_LOGIN_ATTEMPTS';")} | grep -E '^\\s*\\S+$' | tail -1`,
    parseRegex: '(\\d+|UNLIMITED)',
    writeCommand: (v) => `${oraCmd(`ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS ${v};`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'oracle-password-life',
    name: 'PASSWORD_LIFE_TIME',
    description: '密码有效期（天），建议 90 天',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'number',
    defaultValue: '180',
    recommendedValue: '90',
    riskLevel: 'high',
    validation: { min: 1, max: 365 },
    readCommand: `${oraCmd("SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='PASSWORD_LIFE_TIME';")} | grep -E '^\\s*\\S+$' | tail -1`,
    parseRegex: '(\\d+|UNLIMITED)',
    writeCommand: (v) => `${oraCmd(`ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME ${v};`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'oracle-password-complexity',
    name: 'PASSWORD_VERIFY_FUNCTION',
    description: '密码复杂度校验函数，建议启用',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'enum',
    enumValues: ['NULL', 'ora12c_verify_function', 'ora12c_strong_verify_function'],
    defaultValue: 'NULL',
    recommendedValue: 'ora12c_verify_function',
    riskLevel: 'high',
    readCommand: `${oraCmd("SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='PASSWORD_VERIFY_FUNCTION';")} | grep -E '^\\s*\\S+$' | tail -1`,
    parseRegex: '(NULL|ora12c_verify_function|ora12c_strong_verify_function|\\S+)',
    writeCommand: (v) => `${oraCmd(`ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION ${v};`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'oracle-remote-login',
    name: 'REMOTE_LOGIN_PASSWORDFILE',
    description: '远程登录密码文件类型（NONE/EXCLUSIVE/SHARED），建议 EXCLUSIVE',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'enum',
    enumValues: ['NONE', 'EXCLUSIVE', 'SHARED'],
    defaultValue: 'EXCLUSIVE',
    recommendedValue: 'EXCLUSIVE',
    riskLevel: 'medium',
    readCommand: `${oraCmd("SHOW PARAMETER remote_login_passwordfile;")} | grep -i remote_login_passwordfile | awk '{print $NF}'`,
    parseRegex: '(NONE|EXCLUSIVE|SHARED)',
    writeCommand: (v) => `${oraCmd(`ALTER SYSTEM SET remote_login_passwordfile='${v}' SCOPE=SPFILE;`)}`,
    backupCommand: 'true',
    restartCommand: `su - oracle -c "echo 'SHUTDOWN IMMEDIATE;\\nSTARTUP;' | sqlplus -s / as sysdba" 2>/dev/null`,
    restartService: 'oracle',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'oracle-os-auth',
    name: 'OS_AUTHENT_PREFIX',
    description: '操作系统认证前缀，建议设为空以禁用 OS 认证',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'string',
    defaultValue: 'ops$',
    recommendedValue: '',
    riskLevel: 'high',
    readCommand: `${oraCmd("SHOW PARAMETER os_authent_prefix;")} | grep -i os_authent_prefix | awk '{print $NF}'`,
    parseRegex: 'os_authent_prefix\\s+\\S+\\s+(\\S*)',
    writeCommand: (v) => `${oraCmd(`ALTER SYSTEM SET os_authent_prefix='${v}' SCOPE=SPFILE;`)}`,
    backupCommand: 'true',
    restartCommand: `su - oracle -c "echo 'SHUTDOWN IMMEDIATE;\\nSTARTUP;' | sqlplus -s / as sysdba" 2>/dev/null`,
    restartService: 'oracle',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'oracle-utl-file-dir',
    name: 'UTL_FILE_DIR',
    description: 'UTL_FILE 可访问的目录，建议清空防止文件读写滥用',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'string',
    defaultValue: '*',
    recommendedValue: '',
    riskLevel: 'critical',
    readCommand: `${oraCmd("SHOW PARAMETER utl_file_dir;")} | grep -i utl_file_dir | awk '{print $NF}'`,
    parseRegex: 'utl_file_dir\\s+\\S+\\s+(.*)',
    writeCommand: (v) => `${oraCmd(`ALTER SYSTEM SET utl_file_dir='${v}' SCOPE=SPFILE;`)}`,
    backupCommand: 'true',
    restartCommand: `su - oracle -c "echo 'SHUTDOWN IMMEDIATE;\\nSTARTUP;' | sqlplus -s / as sysdba" 2>/dev/null`,
    restartService: 'oracle',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'oracle-sec-encryption',
    name: 'NETWORK_ENCRYPTION',
    description: '网络传输加密（SQLNET.ENCRYPTION_SERVER），建议 REQUIRED',
    filePath: '$ORACLE_HOME/network/admin/sqlnet.ora',
    type: 'enum',
    enumValues: ['REJECTED', 'ACCEPTED', 'REQUESTED', 'REQUIRED'],
    defaultValue: 'ACCEPTED',
    recommendedValue: 'REQUIRED',
    riskLevel: 'high',
    readCommand: `grep -iE '^\\s*SQLNET.ENCRYPTION_SERVER' $ORACLE_HOME/network/admin/sqlnet.ora 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo 'ACCEPTED'`,
    parseRegex: '(REJECTED|ACCEPTED|REQUESTED|REQUIRED)',
    writeCommand: (v) => `grep -qi 'SQLNET.ENCRYPTION_SERVER' $ORACLE_HOME/network/admin/sqlnet.ora && sed -i "s/^.*SQLNET.ENCRYPTION_SERVER.*/SQLNET.ENCRYPTION_SERVER = ${v}/" $ORACLE_HOME/network/admin/sqlnet.ora || echo "SQLNET.ENCRYPTION_SERVER = ${v}" >> $ORACLE_HOME/network/admin/sqlnet.ora`,
    backupCommand: `cp -n $ORACLE_HOME/network/admin/sqlnet.ora $ORACLE_HOME/network/admin/sqlnet.ora.bak.$(date +%Y%m%d%H%M%S) 2>/dev/null; true`,
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'oracle-idle-timeout',
    name: 'IDLE_TIME',
    description: '空闲超时时间（分钟），建议不超过 30 分钟',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'number',
    defaultValue: 'UNLIMITED',
    recommendedValue: '30',
    riskLevel: 'medium',
    validation: { min: 1, max: 1440 },
    readCommand: `${oraCmd("SELECT limit FROM dba_profiles WHERE profile='DEFAULT' AND resource_name='IDLE_TIME';")} | grep -E '^\\s*\\S+$' | tail -1`,
    parseRegex: '(\\d+|UNLIMITED)',
    writeCommand: (v) => `${oraCmd(`ALTER PROFILE DEFAULT LIMIT IDLE_TIME ${v};`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'oracle-default-tablespace',
    name: 'DEFAULT_TABLESPACE 权限',
    description: '普通用户不应拥有 SYSTEM/SYSAUX 表空间的默认使用权',
    filePath: '$ORACLE_HOME/dbs/init.ora',
    type: 'enum',
    enumValues: ['安全', '不安全'],
    defaultValue: '不安全',
    recommendedValue: '安全',
    riskLevel: 'medium',
    readCommand: `${oraCmd("SELECT COUNT(*) FROM dba_users WHERE default_tablespace IN ('SYSTEM','SYSAUX') AND username NOT IN ('SYS','SYSTEM','DBSNMP','OUTLN');")} | grep -E '^\\s*\\d+$' | tail -1 | awk '{if($1==0)print "安全"; else print "不安全"}'`,
    parseRegex: '(安全|不安全)',
    writeCommand: (_v) => `echo '请手动将普通用户的默认表空间迁移到非 SYSTEM/SYSAUX 表空间'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 访问控制',
  },
];

// ─── SQL Server ───

const sqlcmd = (sql: string) => `/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -Q "${sql}" 2>/dev/null`;

const mssqlItems: BaselineConfigItem[] = [
  {
    id: 'mssql-auth-mode',
    name: '身份验证模式',
    description: '建议使用 Windows+SQL 混合认证或仅 Windows 认证',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['Windows', 'Mixed', 'SQL'],
    defaultValue: 'Mixed',
    recommendedValue: 'Mixed',
    riskLevel: 'medium',
    readCommand: `${sqlcmd("SELECT SERVERPROPERTY('IsIntegratedSecurityOnly')")} | grep -E '^\\s*[01]' | tr -d ' ' | awk '{if($1==1)print "Windows"; else print "Mixed"}'`,
    parseRegex: '(Windows|Mixed|SQL)',
    writeCommand: (_v) => `echo '身份验证模式需通过 SQL Server Configuration Manager 修改'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'mssql-sa-disabled',
    name: 'SA 账户状态',
    description: '建议禁用或重命名 SA 内置管理员账户',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已禁用', '已启用'],
    defaultValue: '已启用',
    recommendedValue: '已禁用',
    riskLevel: 'critical',
    readCommand: `${sqlcmd("SELECT is_disabled FROM sys.sql_logins WHERE name='sa'")} | grep -E '^\\s*[01]' | tr -d ' ' | awk '{if($1==1)print "已禁用"; else print "已启用"}'`,
    parseRegex: '(已禁用|已启用)',
    writeCommand: (v) => {
      if (v === '已禁用') {
        return `${sqlcmd("ALTER LOGIN sa DISABLE")}`;
      }
      return `${sqlcmd("ALTER LOGIN sa ENABLE")}`;
    },
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'mssql-audit',
    name: '审计功能',
    description: '建议启用 SQL Server 审计功能记录关键操作',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `${sqlcmd("SELECT COUNT(*) FROM sys.server_audits WHERE is_state_enabled=1")} | grep -E '^\\s*\\d+' | tr -d ' ' | awk '{if($1>0)print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请通过 SSMS 或 T-SQL 创建并启用服务器审计'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'mssql-xp-cmdshell',
    name: 'xp_cmdshell',
    description: '禁用 xp_cmdshell 防止通过 SQL 执行系统命令',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已启用', '已禁用'],
    defaultValue: '已禁用',
    recommendedValue: '已禁用',
    riskLevel: 'critical',
    readCommand: `${sqlcmd("EXEC sp_configure 'xp_cmdshell'")} | grep -E 'run_value' -A1 | tail -1 | awk '{print $NF}' | awk '{if($1==0)print "已禁用"; else print "已启用"}'`,
    parseRegex: '(已启用|已禁用)',
    writeCommand: (v) => {
      if (v === '已禁用') {
        return `${sqlcmd("EXEC sp_configure 'show advanced options',1; RECONFIGURE; EXEC sp_configure 'xp_cmdshell',0; RECONFIGURE;")}`;
      }
      return `${sqlcmd("EXEC sp_configure 'show advanced options',1; RECONFIGURE; EXEC sp_configure 'xp_cmdshell',1; RECONFIGURE;")}`;
    },
    backupCommand: 'true',
    complianceRef: '等保2.0 安全计算环境',
  },
  {
    id: 'mssql-remote-access',
    name: 'remote access',
    description: '禁用远程服务器访问，减少攻击面',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已启用', '已禁用'],
    defaultValue: '已启用',
    recommendedValue: '已禁用',
    riskLevel: 'high',
    readCommand: `${sqlcmd("EXEC sp_configure 'remote access'")} | grep -E 'config_value|run_value' -A1 | tail -1 | awk '{print $NF}' | awk '{if($1==0)print "已禁用"; else print "已启用"}'`,
    parseRegex: '(已启用|已禁用)',
    writeCommand: (v) => {
      if (v === '已禁用') {
        return `${sqlcmd("EXEC sp_configure 'remote access',0; RECONFIGURE;")}`;
      }
      return `${sqlcmd("EXEC sp_configure 'remote access',1; RECONFIGURE;")}`;
    },
    backupCommand: 'true',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'mssql-clr-enabled',
    name: 'CLR 集成',
    description: '禁用 CLR 集成，防止运行不受信任的 .NET 程序集',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已启用', '已禁用'],
    defaultValue: '已禁用',
    recommendedValue: '已禁用',
    riskLevel: 'high',
    readCommand: `${sqlcmd("EXEC sp_configure 'clr enabled'")} | grep -E 'run_value' -A1 | tail -1 | awk '{print $NF}' | awk '{if($1==0)print "已禁用"; else print "已启用"}'`,
    parseRegex: '(已启用|已禁用)',
    writeCommand: (v) => {
      if (v === '已禁用') {
        return `${sqlcmd("EXEC sp_configure 'clr enabled',0; RECONFIGURE;")}`;
      }
      return `${sqlcmd("EXEC sp_configure 'clr enabled',1; RECONFIGURE;")}`;
    },
    backupCommand: 'true',
    complianceRef: '等保2.0 安全计算环境',
  },
  {
    id: 'mssql-tde',
    name: '透明数据加密 (TDE)',
    description: '启用 TDE 加密数据库文件，保护静态数据',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `${sqlcmd("SELECT COUNT(*) FROM sys.dm_database_encryption_keys WHERE encryption_state=3")} | grep -E '^\\s*\\d+' | tr -d ' ' | awk '{if($1>0)print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请通过 T-SQL 为各数据库单独启用 TDE 加密'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 数据保密性',
  },
  {
    id: 'mssql-password-policy',
    name: '密码策略强制',
    description: '确保所有 SQL 登录名启用密码策略检查',
    filePath: '/var/opt/mssql/mssql.conf',
    type: 'enum',
    enumValues: ['全部启用', '部分未启用'],
    defaultValue: '部分未启用',
    recommendedValue: '全部启用',
    riskLevel: 'high',
    readCommand: `${sqlcmd("SELECT COUNT(*) FROM sys.sql_logins WHERE is_policy_checked=0 AND name NOT IN ('sa')")} | grep -E '^\\s*\\d+' | tr -d ' ' | awk '{if($1==0)print "全部启用"; else print "部分未启用"}'`,
    parseRegex: '(全部启用|部分未启用)',
    writeCommand: (_v) => `echo '请通过 ALTER LOGIN 为每个登录名单独启用 CHECK_POLICY=ON'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
];

// ─── 达梦 DM ───

const dmIni = '/opt/dmdbms/data/DAMENG/dm.ini';
const dmCmd = (sql: string) => `su - dmdba -c "echo '${sql}' | disql SYSDBA/SYSDBA001" 2>/dev/null`;

const damengItems: BaselineConfigItem[] = [
  {
    id: 'dm-pwd-policy',
    name: 'PWD_POLICY',
    description: '密码策略级别（0-5），建议设为 2 以上',
    filePath: dmIni,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '2',
    riskLevel: 'critical',
    validation: { min: 0, max: 5 },
    readCommand: `grep -E '^\\s*PWD_POLICY' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'PWD_POLICY', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'dm-pwd-min-len',
    name: 'PWD_MIN_LEN',
    description: '密码最小长度，建议不少于 8 位',
    filePath: dmIni,
    type: 'number',
    defaultValue: '6',
    recommendedValue: '8',
    riskLevel: 'high',
    validation: { min: 1, max: 128 },
    readCommand: `grep -E '^\\s*PWD_MIN_LEN' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '6'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'PWD_MIN_LEN', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'dm-failed-login',
    name: 'LOGIN_FAILED_ATTEMPTS',
    description: '登录失败锁定次数，建议不超过 5 次',
    filePath: dmIni,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '5',
    riskLevel: 'high',
    validation: { min: 0, max: 100 },
    readCommand: `${dmCmd("SELECT PARA_VALUE FROM V\\$DM_INI WHERE PARA_NAME='LOGIN_FAILED_ATTEMPTS';")} | grep -E '^\\s*\\d+' | tr -d ' ' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'LOGIN_FAILED_ATTEMPTS', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'dm-audit',
    name: 'ENABLE_AUDIT',
    description: '启用审计功能，记录关键操作',
    filePath: dmIni,
    type: 'enum',
    enumValues: ['1', '0'],
    defaultValue: '0',
    recommendedValue: '1',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*ENABLE_AUDIT' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0'`,
    parseRegex: '([01])',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'ENABLE_AUDIT', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'dm-encrypt',
    name: 'ENABLE_ENCRYPT',
    description: '启用通信加密，保护数据传输安全',
    filePath: dmIni,
    type: 'enum',
    enumValues: ['1', '0'],
    defaultValue: '0',
    recommendedValue: '1',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*ENABLE_ENCRYPT' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0'`,
    parseRegex: '([01])',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'ENABLE_ENCRYPT', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'dm-session-timeout',
    name: 'SESSION_TIMEOUT',
    description: '会话超时时间（秒），建议设为 1800 秒',
    filePath: dmIni,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '1800',
    riskLevel: 'medium',
    validation: { min: 0, max: 86400 },
    readCommand: `grep -E '^\\s*SESSION_TIMEOUT' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'SESSION_TIMEOUT', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'dm-max-sessions',
    name: 'MAX_SESSIONS',
    description: '最大并发会话数，合理配置防止资源耗尽',
    filePath: dmIni,
    type: 'number',
    defaultValue: '100',
    recommendedValue: '200',
    riskLevel: 'medium',
    validation: { min: 10, max: 100000 },
    readCommand: `grep -E '^\\s*MAX_SESSIONS' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '100'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'MAX_SESSIONS', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'dm-log-level',
    name: 'SVR_LOG_LEVEL',
    description: '服务器日志级别，建议 INFO 以上',
    filePath: dmIni,
    type: 'enum',
    enumValues: ['0', '1', '2', '3'],
    defaultValue: '1',
    recommendedValue: '2',
    riskLevel: 'low',
    readCommand: `grep -E '^\\s*SVR_LOG_LEVEL' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '1'`,
    parseRegex: '([0-3])',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'SVR_LOG_LEVEL', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'dm-ip-check',
    name: 'ENABLE_IP_CHECK',
    description: '启用 IP 白名单检查，限制客户端访问来源',
    filePath: dmIni,
    type: 'enum',
    enumValues: ['1', '0'],
    defaultValue: '0',
    recommendedValue: '1',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*ENABLE_IP_CHECK' ${dmIni} 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0'`,
    parseRegex: '([01])',
    writeCommand: (v) => sedOrAppendEq(dmIni, 'ENABLE_IP_CHECK', v),
    backupCommand: backup(dmIni),
    restartCommand: 'systemctl restart DmServiceDMSERVER 2>/dev/null',
    restartService: 'DmServiceDMSERVER',
    complianceRef: '等保2.0 访问控制',
  },
  {
    id: 'dm-tde',
    name: '透明数据加密 (TDE)',
    description: '启用透明数据加密保护静态数据安全',
    filePath: dmIni,
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `${dmCmd("SELECT COUNT(*) FROM V\\$DM_INI WHERE PARA_NAME='ENABLE_TDE' AND PARA_VALUE='1';")} | grep -E '^\\s*\\d+' | tr -d ' ' | awk '{if($1>0)print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请参考达梦文档配置 TDE 加密密钥和表空间加密'; true`,
    backupCommand: backup(dmIni),
    complianceRef: '等保2.0 数据保密性',
  },
];

// ─── KingbaseES ───

const kbConf = '/opt/Kingbase/ES/V8/data/kingbase.conf';
const kbHba = '/opt/Kingbase/ES/V8/data/pg_hba.conf';

const kingbaseItems: BaselineConfigItem[] = [
  {
    id: 'kb-listen-addresses',
    name: 'listen_addresses',
    description: '监听地址，建议绑定特定 IP 而非 *',
    filePath: kbConf,
    type: 'string',
    defaultValue: '*',
    recommendedValue: 'localhost',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*listen_addresses' ${kbConf} 2>/dev/null | head -1 || echo "#listen_addresses = '*'"`,
    parseRegex: "listen_addresses\\s*=\\s*'([^']*)'",
    writeCommand: (v) => `sed -i "s/^#*\\s*listen_addresses.*/listen_addresses = '${v}'/" ${kbConf} || echo "listen_addresses = '${v}'" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl restart kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'kb-ssl',
    name: 'ssl',
    description: '启用 SSL 加密连接',
    filePath: kbConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*ssl\\s*=' ${kbConf} 2>/dev/null | head -1 || echo '#ssl = off'`,
    parseRegex: 'ssl\\s*=\\s*(on|off)',
    writeCommand: (v) => `sed -i "s/^#*\\s*ssl\\s*=.*/ssl = ${v}/" ${kbConf} || echo "ssl = ${v}" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl restart kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'kb-password-encryption',
    name: 'password_encryption',
    description: '密码加密算法，建议 scram-sha-256',
    filePath: kbConf,
    type: 'enum',
    enumValues: ['scram-sha-256', 'md5'],
    defaultValue: 'md5',
    recommendedValue: 'scram-sha-256',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*password_encryption' ${kbConf} 2>/dev/null | head -1 || echo "#password_encryption = 'md5'"`,
    parseRegex: "password_encryption\\s*=\\s*'?([\\w-]+)",
    writeCommand: (v) => `sed -i "s/^#*\\s*password_encryption.*/password_encryption = '${v}'/" ${kbConf} || echo "password_encryption = '${v}'" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl reload kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'kb-log-connections',
    name: 'log_connections',
    description: '记录连接日志，便于审计',
    filePath: kbConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_connections' ${kbConf} 2>/dev/null | head -1 || echo '#log_connections = off'`,
    parseRegex: 'log_connections\\s*=\\s*(on|off)',
    writeCommand: (v) => `sed -i "s/^#*\\s*log_connections.*/log_connections = ${v}/" ${kbConf} || echo "log_connections = ${v}" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl reload kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'kb-log-statement',
    name: 'log_statement',
    description: '记录 SQL 语句类型（none/ddl/mod/all）',
    filePath: kbConf,
    type: 'enum',
    enumValues: ['none', 'ddl', 'mod', 'all'],
    defaultValue: 'none',
    recommendedValue: 'ddl',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_statement' ${kbConf} 2>/dev/null | head -1 || echo "#log_statement = 'none'"`,
    parseRegex: "log_statement\\s*=\\s*'?(none|ddl|mod|all)",
    writeCommand: (v) => `sed -i "s/^#*\\s*log_statement.*/log_statement = '${v}'/" ${kbConf} || echo "log_statement = '${v}'" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl reload kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'kb-hba-trust',
    name: 'pg_hba trust 条目数',
    description: 'pg_hba.conf 中 trust 认证条目数量，建议为 0',
    filePath: kbHba,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '0',
    riskLevel: 'critical',
    readCommand: `grep -cE '^\\s*(local|host).*trust' ${kbHba} 2>/dev/null || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (_v) => `sed -i 's/\\btrust\\b/scram-sha-256/g' ${kbHba}`,
    backupCommand: backup(kbHba),
    restartCommand: 'systemctl reload kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'kb-max-connections',
    name: 'max_connections',
    description: '最大并发连接数',
    filePath: kbConf,
    type: 'number',
    defaultValue: '100',
    recommendedValue: '200',
    riskLevel: 'medium',
    validation: { min: 10, max: 100000 },
    readCommand: `grep -E '^\\s*max_connections' ${kbConf} 2>/dev/null | head -1 || echo '#max_connections = 100'`,
    parseRegex: 'max_connections\\s*=\\s*(\\d+)',
    writeCommand: (v) => `sed -i "s/^#*\\s*max_connections.*/max_connections = ${v}/" ${kbConf} || echo "max_connections = ${v}" >> ${kbConf}`,
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl restart kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'kb-audit',
    name: 'kdb_audit',
    description: 'KingbaseES 内置审计模块，建议启用',
    filePath: kbConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*shared_preload_libraries' ${kbConf} 2>/dev/null | grep -q 'kdb_audit' && echo 'on' || echo 'off'`,
    parseRegex: '(on|off)',
    writeCommand: (v) => {
      if (v === 'on') {
        return `grep -q 'shared_preload_libraries' ${kbConf} && sed -i "s/shared_preload_libraries\\s*=\\s*'\\([^']*\\)'/shared_preload_libraries = '\\1,kdb_audit'/" ${kbConf} || echo "shared_preload_libraries = 'kdb_audit'" >> ${kbConf}`;
      }
      return `sed -i "s/,kdb_audit//g; s/kdb_audit,//g; s/kdb_audit//g" ${kbConf}`;
    },
    backupCommand: backup(kbConf),
    restartCommand: 'systemctl restart kingbase 2>/dev/null',
    restartService: 'kingbase',
    complianceRef: '等保2.0 安全审计',
  },
];

// ─── GBase ───

const gbaseItems: BaselineConfigItem[] = [
  {
    id: 'gbase-auth',
    name: '认证模式',
    description: '数据库认证模式，建议启用密码认证',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '已启用',
    recommendedValue: '已启用',
    riskLevel: 'critical',
    readCommand: `gbase -u root -e "SELECT @@authentication_policy" 2>/dev/null | tail -1 || echo '已启用'`,
    parseRegex: '(已启用|未启用|\\S+)',
    writeCommand: (_v) => `echo '请通过 GBase 管理工具配置认证策略'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'gbase-listen',
    name: '监听地址',
    description: '数据库监听地址，建议绑定 127.0.0.1',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'string',
    defaultValue: '0.0.0.0',
    recommendedValue: '127.0.0.1',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*bind-address' /opt/gbase/config/gbase.conf 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo '0.0.0.0'`,
    parseRegex: '(\\S+)',
    writeCommand: (v) => sedOrAppendEq('/opt/gbase/config/gbase.conf', 'bind-address', v),
    backupCommand: backup('/opt/gbase/config/gbase.conf'),
    restartCommand: 'systemctl restart gbase 2>/dev/null',
    restartService: 'gbase',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'gbase-audit',
    name: '审计日志',
    description: '启用审计日志记录数据库操作',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*audit_log' /opt/gbase/config/gbase.conf 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' | awk '{if($1=="ON" || $1=="1")print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (v) => sedOrAppendEq('/opt/gbase/config/gbase.conf', 'audit_log', v === '已启用' ? 'ON' : 'OFF'),
    backupCommand: backup('/opt/gbase/config/gbase.conf'),
    restartCommand: 'systemctl restart gbase 2>/dev/null',
    restartService: 'gbase',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'gbase-ssl',
    name: 'SSL 加密',
    description: '启用 SSL 加密客户端通信',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*ssl' /opt/gbase/config/gbase.conf 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || echo 'OFF'`,
    parseRegex: '(ON|OFF)',
    writeCommand: (v) => sedOrAppendEq('/opt/gbase/config/gbase.conf', 'ssl', v),
    backupCommand: backup('/opt/gbase/config/gbase.conf'),
    restartCommand: 'systemctl restart gbase 2>/dev/null',
    restartService: 'gbase',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'gbase-max-connections',
    name: 'max_connections',
    description: '最大并发连接数',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'number',
    defaultValue: '200',
    recommendedValue: '500',
    riskLevel: 'medium',
    validation: { min: 10, max: 100000 },
    readCommand: `gbase -u root -e "SHOW VARIABLES LIKE 'max_connections'" 2>/dev/null | grep -i max_connections | awk '{print $2}' || echo '200'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => sedOrAppendEq('/opt/gbase/config/gbase.conf', 'max_connections', v),
    backupCommand: backup('/opt/gbase/config/gbase.conf'),
    restartCommand: 'systemctl restart gbase 2>/dev/null',
    restartService: 'gbase',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'gbase-password-policy',
    name: '密码策略',
    description: '密码复杂度策略，建议启用',
    filePath: '/opt/gbase/config/gbase.conf',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `gbase -u root -e "SHOW VARIABLES LIKE 'validate_password%'" 2>/dev/null | grep -c policy | awk '{if($1>0)print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请通过 GBase 管理工具配置 validate_password 插件'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
];

// ─── OceanBase ───

const obMysql = (sql: string) => `mysql -h127.0.0.1 -P2881 -uroot -e "${sql}" 2>/dev/null`;

const oceanbaseItems: BaselineConfigItem[] = [
  {
    id: 'ob-ssl',
    name: 'ssl_client_authentication',
    description: '启用 SSL 客户端认证，加密通信',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'high',
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'ssl_client_authentication'")} | grep -i ssl_client_authentication | awk '{print $2}' || echo 'OFF'`,
    parseRegex: '(ON|OFF)',
    writeCommand: (v) => `${obMysql(`ALTER SYSTEM SET ssl_client_authentication='${v}'`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'ob-password-verify',
    name: 'validate_password_policy',
    description: '密码验证策略，建议启用',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'enum',
    enumValues: ['LOW', 'MEDIUM'],
    defaultValue: 'LOW',
    recommendedValue: 'MEDIUM',
    riskLevel: 'high',
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'validate_password_policy'")} | grep -i validate_password_policy | awk '{print $2}' || echo 'LOW'`,
    parseRegex: '(LOW|MEDIUM)',
    writeCommand: (v) => `${obMysql(`SET GLOBAL validate_password_policy='${v}'`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'ob-audit',
    name: 'ob_enable_sql_audit',
    description: 'SQL 审计功能，建议启用以记录所有 SQL',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'enum',
    enumValues: ['true', 'false'],
    defaultValue: 'true',
    recommendedValue: 'true',
    riskLevel: 'medium',
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'ob_enable_sql_audit'")} | grep -i ob_enable_sql_audit | awk '{print $2}' || echo 'true'`,
    parseRegex: '(true|false|ON|OFF)',
    writeCommand: (v) => `${obMysql(`ALTER SYSTEM SET ob_enable_sql_audit='${v}'`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'ob-max-connections',
    name: 'max_connections',
    description: '最大并发连接数',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'number',
    defaultValue: '2048',
    recommendedValue: '2048',
    riskLevel: 'medium',
    validation: { min: 10, max: 1000000 },
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'max_connections'")} | grep -i max_connections | awk '{print $2}' || echo '2048'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `${obMysql(`SET GLOBAL max_connections=${v}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'ob-failed-login',
    name: 'connection_control_failed_connections_threshold',
    description: '登录失败延迟阈值，建议设为 3 次以上开始延迟',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'number',
    defaultValue: '0',
    recommendedValue: '3',
    riskLevel: 'high',
    validation: { min: 0, max: 100 },
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'connection_control_failed_connections_threshold'")} | grep -i threshold | awk '{print $2}' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `${obMysql(`SET GLOBAL connection_control_failed_connections_threshold=${v}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'ob-recyclebin',
    name: 'recyclebin',
    description: '回收站功能，建议开启以防止误删除',
    filePath: '/home/admin/oceanbase/etc/observer.config.bin',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'medium',
    readCommand: `${obMysql("SHOW VARIABLES LIKE 'recyclebin'")} | grep -i recyclebin | awk '{print $2}' || echo 'OFF'`,
    parseRegex: '(ON|OFF)',
    writeCommand: (v) => `${obMysql(`ALTER SYSTEM SET recyclebin='${v}'`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 数据备份恢复',
  },
];

// ─── openGauss ───

const ogConf = '/opt/openGauss/data/postgresql.conf';
const ogHba = '/opt/openGauss/data/pg_hba.conf';

const openGaussItems: BaselineConfigItem[] = [
  {
    id: 'og-listen-addresses',
    name: 'listen_addresses',
    description: '监听地址，建议绑定特定 IP',
    filePath: ogConf,
    type: 'string',
    defaultValue: 'localhost',
    recommendedValue: 'localhost',
    riskLevel: 'critical',
    readCommand: `grep -E '^\\s*listen_addresses' ${ogConf} 2>/dev/null | head -1 || echo "#listen_addresses = 'localhost'"`,
    parseRegex: "listen_addresses\\s*=\\s*'([^']*)'",
    writeCommand: (v) => `sed -i "s/^#*\\s*listen_addresses.*/listen_addresses = '${v}'/" ${ogConf} || echo "listen_addresses = '${v}'" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl restart -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 网络安全',
  },
  {
    id: 'og-ssl',
    name: 'ssl',
    description: '启用 SSL 加密连接',
    filePath: ogConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*ssl\\s*=' ${ogConf} 2>/dev/null | head -1 || echo '#ssl = off'`,
    parseRegex: 'ssl\\s*=\\s*(on|off)',
    writeCommand: (v) => `sed -i "s/^#*\\s*ssl\\s*=.*/ssl = ${v}/" ${ogConf} || echo "ssl = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl restart -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'og-password-encryption',
    name: 'password_encryption_type',
    description: '密码加密类型（0=md5, 1=sha256+md5, 2=sha256），建议 2',
    filePath: ogConf,
    type: 'enum',
    enumValues: ['0', '1', '2'],
    defaultValue: '1',
    recommendedValue: '2',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*password_encryption_type' ${ogConf} 2>/dev/null | head -1 || echo '#password_encryption_type = 1'`,
    parseRegex: 'password_encryption_type\\s*=\\s*(\\d)',
    writeCommand: (v) => `sed -i "s/^#*\\s*password_encryption_type.*/password_encryption_type = ${v}/" ${ogConf} || echo "password_encryption_type = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl restart -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'og-failed-login',
    name: 'failed_login_attempts',
    description: '登录失败锁定次数，建议设为 10',
    filePath: ogConf,
    type: 'number',
    defaultValue: '10',
    recommendedValue: '10',
    riskLevel: 'high',
    validation: { min: 0, max: 1000 },
    readCommand: `grep -E '^\\s*failed_login_attempts' ${ogConf} 2>/dev/null | head -1 || echo '#failed_login_attempts = 10'`,
    parseRegex: 'failed_login_attempts\\s*=\\s*(\\d+)',
    writeCommand: (v) => `sed -i "s/^#*\\s*failed_login_attempts.*/failed_login_attempts = ${v}/" ${ogConf} || echo "failed_login_attempts = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl reload -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'og-password-reuse-max',
    name: 'password_reuse_max',
    description: '密码重用次数限制，建议不少于 5',
    filePath: ogConf,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '5',
    riskLevel: 'medium',
    validation: { min: 0, max: 1000 },
    readCommand: `grep -E '^\\s*password_reuse_max' ${ogConf} 2>/dev/null | head -1 || echo '#password_reuse_max = 0'`,
    parseRegex: 'password_reuse_max\\s*=\\s*(\\d+)',
    writeCommand: (v) => `sed -i "s/^#*\\s*password_reuse_max.*/password_reuse_max = ${v}/" ${ogConf} || echo "password_reuse_max = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl reload -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'og-log-connections',
    name: 'log_connections',
    description: '记录连接日志',
    filePath: ogConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'off',
    recommendedValue: 'on',
    riskLevel: 'medium',
    readCommand: `grep -E '^\\s*log_connections' ${ogConf} 2>/dev/null | head -1 || echo '#log_connections = off'`,
    parseRegex: 'log_connections\\s*=\\s*(on|off)',
    writeCommand: (v) => `sed -i "s/^#*\\s*log_connections.*/log_connections = ${v}/" ${ogConf} || echo "log_connections = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl reload -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'og-hba-trust',
    name: 'pg_hba trust 条目数',
    description: 'pg_hba.conf 中 trust 条目数量，建议为 0',
    filePath: ogHba,
    type: 'number',
    defaultValue: '0',
    recommendedValue: '0',
    riskLevel: 'critical',
    readCommand: `grep -cE '^\\s*(local|host).*trust' ${ogHba} 2>/dev/null || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (_v) => `sed -i 's/\\btrust\\b/sha256/g' ${ogHba}`,
    backupCommand: backup(ogHba),
    restartCommand: 'gs_ctl reload -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'og-audit',
    name: 'audit_enabled',
    description: 'openGauss 审计功能开关',
    filePath: ogConf,
    type: 'enum',
    enumValues: ['on', 'off'],
    defaultValue: 'on',
    recommendedValue: 'on',
    riskLevel: 'high',
    readCommand: `grep -E '^\\s*audit_enabled' ${ogConf} 2>/dev/null | head -1 || echo '#audit_enabled = on'`,
    parseRegex: 'audit_enabled\\s*=\\s*(on|off)',
    writeCommand: (v) => `sed -i "s/^#*\\s*audit_enabled.*/audit_enabled = ${v}/" ${ogConf} || echo "audit_enabled = ${v}" >> ${ogConf}`,
    backupCommand: backup(ogConf),
    restartCommand: 'gs_ctl reload -D /opt/openGauss/data 2>/dev/null',
    restartService: 'openGauss',
    complianceRef: '等保2.0 安全审计',
  },
];

// ─── TiDB ───

const tidbMysql = (sql: string) => `mysql -h127.0.0.1 -P4000 -uroot -e "${sql}" 2>/dev/null`;

const tidbItems: BaselineConfigItem[] = [
  {
    id: 'tidb-ssl',
    name: 'require_secure_transport',
    description: '强制 SSL 加密连接',
    filePath: '/etc/tidb/tidb.toml',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'high',
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'require_secure_transport'")} | grep -i require_secure_transport | awk '{print $2}' || echo 'OFF'`,
    parseRegex: '(ON|OFF)',
    writeCommand: (v) => `${tidbMysql(`SET GLOBAL require_secure_transport=${v}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 通信安全',
  },
  {
    id: 'tidb-password-validation',
    name: 'validate_password.enable',
    description: '密码复杂度校验，建议启用',
    filePath: '/etc/tidb/tidb.toml',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'ON',
    riskLevel: 'high',
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'validate_password.enable'")} | grep -i validate_password | awk '{print $2}' || echo 'OFF'`,
    parseRegex: '(ON|OFF)',
    writeCommand: (v) => `${tidbMysql(`SET GLOBAL validate_password.enable='${v}'`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
  {
    id: 'tidb-audit-log',
    name: 'tidb_audit_log',
    description: '审计日志，记录所有 SQL 操作',
    filePath: '/etc/tidb/tidb.toml',
    type: 'enum',
    enumValues: ['已启用', '未启用'],
    defaultValue: '未启用',
    recommendedValue: '已启用',
    riskLevel: 'high',
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'tidb_enable_telemetry'")} | grep -i tidb_enable_telemetry | awk '{print $2}'; ${tidbMysql("SELECT COUNT(*) FROM INFORMATION_SCHEMA.CLUSTER_CONFIG WHERE \\`KEY\\`='log.file.filename'")} | tail -1 | awk '{if($1>0)print "已启用"; else print "未启用"}'`,
    parseRegex: '(已启用|未启用)',
    writeCommand: (_v) => `echo '请通过 TiDB Dashboard 或配置文件启用审计日志插件'; true`,
    backupCommand: 'true',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'tidb-max-connections',
    name: 'max_connections',
    description: '最大并发连接数',
    filePath: '/etc/tidb/tidb.toml',
    type: 'number',
    defaultValue: '0',
    recommendedValue: '1000',
    riskLevel: 'medium',
    validation: { min: 0, max: 1000000 },
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'max_connections'")} | grep -i max_connections | awk '{print $2}' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `${tidbMysql(`SET GLOBAL max_connections=${v}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 资源控制',
  },
  {
    id: 'tidb-general-log',
    name: 'tidb_general_log',
    description: '通用查询日志，调试和审计用途',
    filePath: '/etc/tidb/tidb.toml',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    defaultValue: 'OFF',
    recommendedValue: 'OFF',
    riskLevel: 'low',
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'tidb_general_log'")} | grep -i tidb_general_log | awk '{print $2}' || echo 'OFF'`,
    parseRegex: '(ON|OFF|0|1)',
    writeCommand: (v) => `${tidbMysql(`SET GLOBAL tidb_general_log=${v === 'ON' ? 1 : 0}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 安全审计',
  },
  {
    id: 'tidb-password-reuse',
    name: 'password_reuse_interval',
    description: '密码重用间隔（天），建议不小于 90 天',
    filePath: '/etc/tidb/tidb.toml',
    type: 'number',
    defaultValue: '0',
    recommendedValue: '90',
    riskLevel: 'medium',
    validation: { min: 0, max: 3650 },
    readCommand: `${tidbMysql("SHOW VARIABLES LIKE 'password_reuse_interval'")} | grep -i password_reuse_interval | awk '{print $2}' || echo '0'`,
    parseRegex: '(\\d+)',
    writeCommand: (v) => `${tidbMysql(`SET GLOBAL password_reuse_interval=${v}`)}`,
    backupCommand: 'true',
    complianceRef: '等保2.0 身份鉴别',
  },
];

// ─── 导出分类 ───

export const databaseBaselineCategories: BaselineCategory[] = [
  {
    id: 'db-mysql',
    title: 'MySQL / MariaDB 安全基线',
    icon: 'Data',
    hint: '适用于 MySQL 5.7+/8.0+ 及 MariaDB 10.x+',
    items: mysqlItems,
  },
  {
    id: 'db-postgresql',
    title: 'PostgreSQL 安全基线',
    icon: 'Data',
    hint: '适用于 PostgreSQL 12+',
    items: postgresqlItems,
  },
  {
    id: 'db-redis',
    title: 'Redis 安全基线',
    icon: 'Data',
    hint: '适用于 Redis 5.0+/6.0+/7.0+',
    items: redisItems,
  },
  {
    id: 'db-mongodb',
    title: 'MongoDB 安全基线',
    icon: 'Data',
    hint: '适用于 MongoDB 4.0+/5.0+/6.0+',
    items: mongodbItems,
  },
  {
    id: 'db-oracle',
    title: 'Oracle 安全基线',
    icon: 'Data',
    hint: '适用于 Oracle 11g/12c/19c/21c',
    items: oracleItems,
  },
  {
    id: 'db-mssql',
    title: 'SQL Server 安全基线',
    icon: 'Data',
    hint: '适用于 SQL Server 2016+（Linux 版）',
    items: mssqlItems,
  },
  {
    id: 'db-dameng',
    title: '达梦 DM 安全基线',
    icon: 'Data',
    hint: '适用于达梦 DM7/DM8',
    items: damengItems,
  },
  {
    id: 'db-kingbase',
    title: '人大金仓 KingbaseES 安全基线',
    icon: 'Data',
    hint: '适用于 KingbaseES V8',
    items: kingbaseItems,
  },
  {
    id: 'db-gbase',
    title: '南大通用 GBase 安全基线',
    icon: 'Data',
    hint: '适用于 GBase 8a/8s',
    items: gbaseItems,
  },
  {
    id: 'db-oceanbase',
    title: 'OceanBase 安全基线',
    icon: 'Data',
    hint: '适用于 OceanBase 3.x/4.x（MySQL 模式）',
    items: oceanbaseItems,
  },
  {
    id: 'db-opengauss',
    title: 'openGauss 安全基线',
    icon: 'Data',
    hint: '适用于 openGauss 2.x/3.x/5.x',
    items: openGaussItems,
  },
  {
    id: 'db-tidb',
    title: 'TiDB 安全基线',
    icon: 'Data',
    hint: '适用于 TiDB 5.x/6.x/7.x（MySQL 兼容）',
    items: tidbItems,
  },
];
